//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mercasmartModel", "FK_RelacionProductoEstablecimiento_Establecimientos", "Establecimientos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mercasmartPersistence.EntityFramework.Establecimientos), "RelacionProductoEstablecimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mercasmartPersistence.EntityFramework.RelacionProductoEstablecimiento), true)]
[assembly: EdmRelationshipAttribute("mercasmartModel", "FK_Productos_Marcas", "Marcas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mercasmartPersistence.EntityFramework.Marcas), "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mercasmartPersistence.EntityFramework.Productos), true)]
[assembly: EdmRelationshipAttribute("mercasmartModel", "FK_Productos_TiposProducto", "TiposProducto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mercasmartPersistence.EntityFramework.TiposProducto), "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mercasmartPersistence.EntityFramework.Productos), true)]
[assembly: EdmRelationshipAttribute("mercasmartModel", "FK_RelacionProductoEstablecimiento_Productos", "Productos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mercasmartPersistence.EntityFramework.Productos), "RelacionProductoEstablecimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mercasmartPersistence.EntityFramework.RelacionProductoEstablecimiento), true)]
[assembly: EdmRelationshipAttribute("mercasmartModel", "RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimiento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mercasmartPersistence.EntityFramework.RelacionProductoEstablecimiento), "RelacionProductoEstablecimientoPrecioVigencia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mercasmartPersistence.EntityFramework.RelacionProductoEstablecimientoPrecioVigencia), true)]

#endregion

namespace mercasmartPersistence.EntityFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mercasmartEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mercasmartEntities object using the connection string found in the 'mercasmartEntities' section of the application configuration file.
        /// </summary>
        public mercasmartEntities() : base("name=mercasmartEntities", "mercasmartEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mercasmartEntities object.
        /// </summary>
        public mercasmartEntities(string connectionString) : base(connectionString, "mercasmartEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mercasmartEntities object.
        /// </summary>
        public mercasmartEntities(EntityConnection connection) : base(connection, "mercasmartEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Establecimientos> Establecimientos
        {
            get
            {
                if ((_Establecimientos == null))
                {
                    _Establecimientos = base.CreateObjectSet<Establecimientos>("Establecimientos");
                }
                return _Establecimientos;
            }
        }
        private ObjectSet<Establecimientos> _Establecimientos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Marcas> Marcas
        {
            get
            {
                if ((_Marcas == null))
                {
                    _Marcas = base.CreateObjectSet<Marcas>("Marcas");
                }
                return _Marcas;
            }
        }
        private ObjectSet<Marcas> _Marcas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Productos> Productos
        {
            get
            {
                if ((_Productos == null))
                {
                    _Productos = base.CreateObjectSet<Productos>("Productos");
                }
                return _Productos;
            }
        }
        private ObjectSet<Productos> _Productos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RelacionProductoEstablecimiento> RelacionProductoEstablecimiento
        {
            get
            {
                if ((_RelacionProductoEstablecimiento == null))
                {
                    _RelacionProductoEstablecimiento = base.CreateObjectSet<RelacionProductoEstablecimiento>("RelacionProductoEstablecimiento");
                }
                return _RelacionProductoEstablecimiento;
            }
        }
        private ObjectSet<RelacionProductoEstablecimiento> _RelacionProductoEstablecimiento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RelacionProductoEstablecimientoPrecioVigencia> RelacionProductoEstablecimientoPrecioVigencia
        {
            get
            {
                if ((_RelacionProductoEstablecimientoPrecioVigencia == null))
                {
                    _RelacionProductoEstablecimientoPrecioVigencia = base.CreateObjectSet<RelacionProductoEstablecimientoPrecioVigencia>("RelacionProductoEstablecimientoPrecioVigencia");
                }
                return _RelacionProductoEstablecimientoPrecioVigencia;
            }
        }
        private ObjectSet<RelacionProductoEstablecimientoPrecioVigencia> _RelacionProductoEstablecimientoPrecioVigencia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TiposProducto> TiposProducto
        {
            get
            {
                if ((_TiposProducto == null))
                {
                    _TiposProducto = base.CreateObjectSet<TiposProducto>("TiposProducto");
                }
                return _TiposProducto;
            }
        }
        private ObjectSet<TiposProducto> _TiposProducto;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Establecimientos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEstablecimientos(Establecimientos establecimientos)
        {
            base.AddObject("Establecimientos", establecimientos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Marcas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarcas(Marcas marcas)
        {
            base.AddObject("Marcas", marcas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Productos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductos(Productos productos)
        {
            base.AddObject("Productos", productos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RelacionProductoEstablecimiento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRelacionProductoEstablecimiento(RelacionProductoEstablecimiento relacionProductoEstablecimiento)
        {
            base.AddObject("RelacionProductoEstablecimiento", relacionProductoEstablecimiento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RelacionProductoEstablecimientoPrecioVigencia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRelacionProductoEstablecimientoPrecioVigencia(RelacionProductoEstablecimientoPrecioVigencia relacionProductoEstablecimientoPrecioVigencia)
        {
            base.AddObject("RelacionProductoEstablecimientoPrecioVigencia", relacionProductoEstablecimientoPrecioVigencia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TiposProducto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTiposProducto(TiposProducto tiposProducto)
        {
            base.AddObject("TiposProducto", tiposProducto);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="Establecimientos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Establecimientos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Establecimientos object.
        /// </summary>
        /// <param name="codigoEstablecimiento">Initial value of the codigoEstablecimiento property.</param>
        /// <param name="nombreEstablecimiento">Initial value of the nombreEstablecimiento property.</param>
        public static Establecimientos CreateEstablecimientos(global::System.String codigoEstablecimiento, global::System.String nombreEstablecimiento)
        {
            Establecimientos establecimientos = new Establecimientos();
            establecimientos.codigoEstablecimiento = codigoEstablecimiento;
            establecimientos.nombreEstablecimiento = nombreEstablecimiento;
            return establecimientos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigoEstablecimiento
        {
            get
            {
                return _codigoEstablecimiento;
            }
            set
            {
                if (_codigoEstablecimiento != value)
                {
                    OncodigoEstablecimientoChanging(value);
                    ReportPropertyChanging("codigoEstablecimiento");
                    _codigoEstablecimiento = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigoEstablecimiento");
                    OncodigoEstablecimientoChanged();
                }
            }
        }
        private global::System.String _codigoEstablecimiento;
        partial void OncodigoEstablecimientoChanging(global::System.String value);
        partial void OncodigoEstablecimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreEstablecimiento
        {
            get
            {
                return _nombreEstablecimiento;
            }
            set
            {
                OnnombreEstablecimientoChanging(value);
                ReportPropertyChanging("nombreEstablecimiento");
                _nombreEstablecimiento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreEstablecimiento");
                OnnombreEstablecimientoChanged();
            }
        }
        private global::System.String _nombreEstablecimiento;
        partial void OnnombreEstablecimientoChanging(global::System.String value);
        partial void OnnombreEstablecimientoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_RelacionProductoEstablecimiento_Establecimientos", "RelacionProductoEstablecimiento")]
        public EntityCollection<RelacionProductoEstablecimiento> RelacionProductoEstablecimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RelacionProductoEstablecimiento>("mercasmartModel.FK_RelacionProductoEstablecimiento_Establecimientos", "RelacionProductoEstablecimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RelacionProductoEstablecimiento>("mercasmartModel.FK_RelacionProductoEstablecimiento_Establecimientos", "RelacionProductoEstablecimiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="Marcas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marcas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Marcas object.
        /// </summary>
        /// <param name="codigoMarca">Initial value of the codigoMarca property.</param>
        /// <param name="nombreMarca">Initial value of the nombreMarca property.</param>
        /// <param name="marcaBlanca">Initial value of the marcaBlanca property.</param>
        public static Marcas CreateMarcas(global::System.String codigoMarca, global::System.String nombreMarca, global::System.Boolean marcaBlanca)
        {
            Marcas marcas = new Marcas();
            marcas.codigoMarca = codigoMarca;
            marcas.nombreMarca = nombreMarca;
            marcas.marcaBlanca = marcaBlanca;
            return marcas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigoMarca
        {
            get
            {
                return _codigoMarca;
            }
            set
            {
                if (_codigoMarca != value)
                {
                    OncodigoMarcaChanging(value);
                    ReportPropertyChanging("codigoMarca");
                    _codigoMarca = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigoMarca");
                    OncodigoMarcaChanged();
                }
            }
        }
        private global::System.String _codigoMarca;
        partial void OncodigoMarcaChanging(global::System.String value);
        partial void OncodigoMarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombreMarca
        {
            get
            {
                return _nombreMarca;
            }
            set
            {
                OnnombreMarcaChanging(value);
                ReportPropertyChanging("nombreMarca");
                _nombreMarca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombreMarca");
                OnnombreMarcaChanged();
            }
        }
        private global::System.String _nombreMarca;
        partial void OnnombreMarcaChanging(global::System.String value);
        partial void OnnombreMarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean marcaBlanca
        {
            get
            {
                return _marcaBlanca;
            }
            set
            {
                OnmarcaBlancaChanging(value);
                ReportPropertyChanging("marcaBlanca");
                _marcaBlanca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("marcaBlanca");
                OnmarcaBlancaChanged();
            }
        }
        private global::System.Boolean _marcaBlanca;
        partial void OnmarcaBlancaChanging(global::System.Boolean value);
        partial void OnmarcaBlancaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_Productos_Marcas", "Productos")]
        public EntityCollection<Productos> Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Productos>("mercasmartModel.FK_Productos_Marcas", "Productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Productos>("mercasmartModel.FK_Productos_Marcas", "Productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="Productos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Productos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Productos object.
        /// </summary>
        /// <param name="idProducto">Initial value of the idProducto property.</param>
        /// <param name="codigoTipoProducto">Initial value of the codigoTipoProducto property.</param>
        /// <param name="codigoMarca">Initial value of the codigoMarca property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        public static Productos CreateProductos(global::System.Int32 idProducto, global::System.String codigoTipoProducto, global::System.String codigoMarca, global::System.String nombre)
        {
            Productos productos = new Productos();
            productos.idProducto = idProducto;
            productos.codigoTipoProducto = codigoTipoProducto;
            productos.codigoMarca = codigoMarca;
            productos.nombre = nombre;
            return productos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProducto
        {
            get
            {
                return _idProducto;
            }
            set
            {
                if (_idProducto != value)
                {
                    OnidProductoChanging(value);
                    ReportPropertyChanging("idProducto");
                    _idProducto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idProducto");
                    OnidProductoChanged();
                }
            }
        }
        private global::System.Int32 _idProducto;
        partial void OnidProductoChanging(global::System.Int32 value);
        partial void OnidProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigoTipoProducto
        {
            get
            {
                return _codigoTipoProducto;
            }
            set
            {
                OncodigoTipoProductoChanging(value);
                ReportPropertyChanging("codigoTipoProducto");
                _codigoTipoProducto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigoTipoProducto");
                OncodigoTipoProductoChanged();
            }
        }
        private global::System.String _codigoTipoProducto;
        partial void OncodigoTipoProductoChanging(global::System.String value);
        partial void OncodigoTipoProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigoMarca
        {
            get
            {
                return _codigoMarca;
            }
            set
            {
                OncodigoMarcaChanging(value);
                ReportPropertyChanging("codigoMarca");
                _codigoMarca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigoMarca");
                OncodigoMarcaChanged();
            }
        }
        private global::System.String _codigoMarca;
        partial void OncodigoMarcaChanging(global::System.String value);
        partial void OncodigoMarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_Productos_Marcas", "Marcas")]
        public Marcas Marcas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marcas>("mercasmartModel.FK_Productos_Marcas", "Marcas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marcas>("mercasmartModel.FK_Productos_Marcas", "Marcas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Marcas> MarcasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marcas>("mercasmartModel.FK_Productos_Marcas", "Marcas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Marcas>("mercasmartModel.FK_Productos_Marcas", "Marcas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_Productos_TiposProducto", "TiposProducto")]
        public TiposProducto TiposProducto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TiposProducto>("mercasmartModel.FK_Productos_TiposProducto", "TiposProducto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TiposProducto>("mercasmartModel.FK_Productos_TiposProducto", "TiposProducto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TiposProducto> TiposProductoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TiposProducto>("mercasmartModel.FK_Productos_TiposProducto", "TiposProducto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TiposProducto>("mercasmartModel.FK_Productos_TiposProducto", "TiposProducto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_RelacionProductoEstablecimiento_Productos", "RelacionProductoEstablecimiento")]
        public EntityCollection<RelacionProductoEstablecimiento> RelacionProductoEstablecimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RelacionProductoEstablecimiento>("mercasmartModel.FK_RelacionProductoEstablecimiento_Productos", "RelacionProductoEstablecimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RelacionProductoEstablecimiento>("mercasmartModel.FK_RelacionProductoEstablecimiento_Productos", "RelacionProductoEstablecimiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="RelacionProductoEstablecimiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RelacionProductoEstablecimiento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RelacionProductoEstablecimiento object.
        /// </summary>
        /// <param name="idRelacion">Initial value of the idRelacion property.</param>
        /// <param name="idProducto">Initial value of the idProducto property.</param>
        /// <param name="codigoEstablecimiento">Initial value of the codigoEstablecimiento property.</param>
        public static RelacionProductoEstablecimiento CreateRelacionProductoEstablecimiento(global::System.Int32 idRelacion, global::System.Int32 idProducto, global::System.String codigoEstablecimiento)
        {
            RelacionProductoEstablecimiento relacionProductoEstablecimiento = new RelacionProductoEstablecimiento();
            relacionProductoEstablecimiento.idRelacion = idRelacion;
            relacionProductoEstablecimiento.idProducto = idProducto;
            relacionProductoEstablecimiento.codigoEstablecimiento = codigoEstablecimiento;
            return relacionProductoEstablecimiento;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idRelacion
        {
            get
            {
                return _idRelacion;
            }
            set
            {
                if (_idRelacion != value)
                {
                    OnidRelacionChanging(value);
                    ReportPropertyChanging("idRelacion");
                    _idRelacion = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idRelacion");
                    OnidRelacionChanged();
                }
            }
        }
        private global::System.Int32 _idRelacion;
        partial void OnidRelacionChanging(global::System.Int32 value);
        partial void OnidRelacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProducto
        {
            get
            {
                return _idProducto;
            }
            set
            {
                OnidProductoChanging(value);
                ReportPropertyChanging("idProducto");
                _idProducto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idProducto");
                OnidProductoChanged();
            }
        }
        private global::System.Int32 _idProducto;
        partial void OnidProductoChanging(global::System.Int32 value);
        partial void OnidProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigoEstablecimiento
        {
            get
            {
                return _codigoEstablecimiento;
            }
            set
            {
                OncodigoEstablecimientoChanging(value);
                ReportPropertyChanging("codigoEstablecimiento");
                _codigoEstablecimiento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigoEstablecimiento");
                OncodigoEstablecimientoChanged();
            }
        }
        private global::System.String _codigoEstablecimiento;
        partial void OncodigoEstablecimientoChanging(global::System.String value);
        partial void OncodigoEstablecimientoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_RelacionProductoEstablecimiento_Establecimientos", "Establecimientos")]
        public Establecimientos Establecimientos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establecimientos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Establecimientos", "Establecimientos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establecimientos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Establecimientos", "Establecimientos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Establecimientos> EstablecimientosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Establecimientos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Establecimientos", "Establecimientos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Establecimientos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Establecimientos", "Establecimientos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_RelacionProductoEstablecimiento_Productos", "Productos")]
        public Productos Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Productos", "Productos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Productos", "Productos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Productos> ProductosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Productos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Productos", "Productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Productos>("mercasmartModel.FK_RelacionProductoEstablecimiento_Productos", "Productos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimientoPrecioVigencia")]
        public EntityCollection<RelacionProductoEstablecimientoPrecioVigencia> RelacionProductoEstablecimientoPrecioVigencia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RelacionProductoEstablecimientoPrecioVigencia>("mercasmartModel.RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimientoPrecioVigencia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RelacionProductoEstablecimientoPrecioVigencia>("mercasmartModel.RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimientoPrecioVigencia", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="RelacionProductoEstablecimientoPrecioVigencia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RelacionProductoEstablecimientoPrecioVigencia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RelacionProductoEstablecimientoPrecioVigencia object.
        /// </summary>
        /// <param name="idRelacionProductoEstablecimiento">Initial value of the idRelacionProductoEstablecimiento property.</param>
        /// <param name="precio">Initial value of the precio property.</param>
        /// <param name="desde">Initial value of the desde property.</param>
        /// <param name="hasta">Initial value of the hasta property.</param>
        public static RelacionProductoEstablecimientoPrecioVigencia CreateRelacionProductoEstablecimientoPrecioVigencia(global::System.Int32 idRelacionProductoEstablecimiento, global::System.Decimal precio, global::System.DateTime desde, global::System.DateTime hasta)
        {
            RelacionProductoEstablecimientoPrecioVigencia relacionProductoEstablecimientoPrecioVigencia = new RelacionProductoEstablecimientoPrecioVigencia();
            relacionProductoEstablecimientoPrecioVigencia.idRelacionProductoEstablecimiento = idRelacionProductoEstablecimiento;
            relacionProductoEstablecimientoPrecioVigencia.precio = precio;
            relacionProductoEstablecimientoPrecioVigencia.desde = desde;
            relacionProductoEstablecimientoPrecioVigencia.hasta = hasta;
            return relacionProductoEstablecimientoPrecioVigencia;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idRelacionProductoEstablecimiento
        {
            get
            {
                return _idRelacionProductoEstablecimiento;
            }
            set
            {
                if (_idRelacionProductoEstablecimiento != value)
                {
                    OnidRelacionProductoEstablecimientoChanging(value);
                    ReportPropertyChanging("idRelacionProductoEstablecimiento");
                    _idRelacionProductoEstablecimiento = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idRelacionProductoEstablecimiento");
                    OnidRelacionProductoEstablecimientoChanged();
                }
            }
        }
        private global::System.Int32 _idRelacionProductoEstablecimiento;
        partial void OnidRelacionProductoEstablecimientoChanging(global::System.Int32 value);
        partial void OnidRelacionProductoEstablecimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal precio
        {
            get
            {
                return _precio;
            }
            set
            {
                if (_precio != value)
                {
                    OnprecioChanging(value);
                    ReportPropertyChanging("precio");
                    _precio = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("precio");
                    OnprecioChanged();
                }
            }
        }
        private global::System.Decimal _precio;
        partial void OnprecioChanging(global::System.Decimal value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime desde
        {
            get
            {
                return _desde;
            }
            set
            {
                if (_desde != value)
                {
                    OndesdeChanging(value);
                    ReportPropertyChanging("desde");
                    _desde = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("desde");
                    OndesdeChanged();
                }
            }
        }
        private global::System.DateTime _desde;
        partial void OndesdeChanging(global::System.DateTime value);
        partial void OndesdeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime hasta
        {
            get
            {
                return _hasta;
            }
            set
            {
                if (_hasta != value)
                {
                    OnhastaChanging(value);
                    ReportPropertyChanging("hasta");
                    _hasta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hasta");
                    OnhastaChanged();
                }
            }
        }
        private global::System.DateTime _hasta;
        partial void OnhastaChanging(global::System.DateTime value);
        partial void OnhastaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimiento")]
        public RelacionProductoEstablecimiento RelacionProductoEstablecimiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RelacionProductoEstablecimiento>("mercasmartModel.RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RelacionProductoEstablecimiento>("mercasmartModel.RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimiento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RelacionProductoEstablecimiento> RelacionProductoEstablecimientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RelacionProductoEstablecimiento>("mercasmartModel.RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RelacionProductoEstablecimiento>("mercasmartModel.RelacionProductoEstablecimientoPrecioVigencia_fk", "RelacionProductoEstablecimiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mercasmartModel", Name="TiposProducto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TiposProducto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TiposProducto object.
        /// </summary>
        /// <param name="codigoTipoProducto">Initial value of the codigoTipoProducto property.</param>
        /// <param name="descripcionProducto">Initial value of the descripcionProducto property.</param>
        public static TiposProducto CreateTiposProducto(global::System.String codigoTipoProducto, global::System.String descripcionProducto)
        {
            TiposProducto tiposProducto = new TiposProducto();
            tiposProducto.codigoTipoProducto = codigoTipoProducto;
            tiposProducto.descripcionProducto = descripcionProducto;
            return tiposProducto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigoTipoProducto
        {
            get
            {
                return _codigoTipoProducto;
            }
            set
            {
                if (_codigoTipoProducto != value)
                {
                    OncodigoTipoProductoChanging(value);
                    ReportPropertyChanging("codigoTipoProducto");
                    _codigoTipoProducto = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigoTipoProducto");
                    OncodigoTipoProductoChanged();
                }
            }
        }
        private global::System.String _codigoTipoProducto;
        partial void OncodigoTipoProductoChanging(global::System.String value);
        partial void OncodigoTipoProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcionProducto
        {
            get
            {
                return _descripcionProducto;
            }
            set
            {
                OndescripcionProductoChanging(value);
                ReportPropertyChanging("descripcionProducto");
                _descripcionProducto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcionProducto");
                OndescripcionProductoChanged();
            }
        }
        private global::System.String _descripcionProducto;
        partial void OndescripcionProductoChanging(global::System.String value);
        partial void OndescripcionProductoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mercasmartModel", "FK_Productos_TiposProducto", "Productos")]
        public EntityCollection<Productos> Productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Productos>("mercasmartModel.FK_Productos_TiposProducto", "Productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Productos>("mercasmartModel.FK_Productos_TiposProducto", "Productos", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
